# Generated by Django 5.2.7 on 2025-11-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Category_description', models.TextField(blank=True, max_length=50, null=True)),
                ('Category_image', models.ImageField(blank=True, null=True, upload_to='category_images')),
            ],
        ),
    ]
