# Generated by Django 5.2.7 on 2025-11-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Tittle', models.CharField(blank=True, max_length=20, null=True)),
                ('Book_author', models.CharField(blank=True, max_length=25, null=True)),
                ('Category', models.CharField(blank=True, max_length=10, null=True)),
                ('Book_Price', models.IntegerField(blank=True, null=True)),
                ('Book_Publisher', models.CharField(blank=True, null=True)),
                ('Book_Description', models.TextField(blank=True, max_length=50, null=True)),
                ('Book_image', models.ImageField(blank=True, null=True, upload_to='book images')),
            ],
        ),
    ]
