# Generated by Django 5.2.7 on 2025-11-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
                ('Confirm_password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
