# Generated by Django 5.2.7 on 2025-11-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Contact_email', models.EmailField(blank=True, max_length=25, null=True)),
                ('Contact_phone', models.IntegerField(blank=True, max_length=20, null=True)),
                ('Contact_city', models.CharField(blank=True, max_length=20, null=True)),
                ('Enquiry_type', models.CharField(blank=True, max_length=20, null=True)),
                ('Contact_message', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
