# Generated by Django 5.2.7 on 2025-11-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(blank=True, max_length=25, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('Book_image', models.ImageField(blank=True, null=True, upload_to='Cart_books')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Contact_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
